export const BOOKING_REQUEST = "BOOKING_REQUEST";
export const BOOKING_SUCCESS = "BOOKING_SUCCESS";
export const BOOKING_FAILURE = "BOOKING_FAILURE";

export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
export const CANCEL_BOOKING_SUCCESS = "CANCEL_BOOKING_SUCCESS";